package com.librarymanagementsys.backend.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

@Document(collection = "Books")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Book {
    @Id
    private String id; // Unique identifier for the book, automatically generated by MongoDB

    private String title;
    private String author;
    private String genre;
    private float rating;
    private String cover;
    private String color;
    private String description;
    private int total_copies;
    private int available_copies;
    private String video;
    private String summary;
    private Date createdAt;

    private Map<String, Integer> ratedBy; // Map of userId to rating value
}
