package com.librarymanagementsys.backend.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "Books")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Book {
    @Id
    private String id; // Unique identifier for the user, automatically generated by MongoDB

    private String title;
    private String author;
    private String genre;
    private int rating;
    private String cover;
    private String color;
    private String description;
    private String total_copies;
    private String available_copies;
    private String video;
    private String summary;
}
