package com.librarymanagementsys.backend.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "Users")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {
    @Id
    private String id; // Unique identifier for the user, automatically generated by MongoDB

    private String fullName;
    private String email;
    private String universityId;
    private String password;

    public User(String fullName, String email, String universityId, String password) {
        this.fullName = fullName;
        this.email = email;
        this.universityId = universityId;
        this.password = password;
    }

}
