package com.librarymanagementsys.backend.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;
import java.util.List;

@Document(collection = "Users")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {
    @Id
    private String id; // Unique identifier for the user, automatically generated by MongoDB

    private String fullName;
    private String email;
    private String universityId;
    private String password;
    private String idCardName;
    private String idCardType;
    private byte[] idCard;
    private int noBooksBorrowed = 0; // Default 0
    private Date registrationDate;
    private String accountStatus = "Verification Pending"; // Default status when a user is registered
    private List<BorrowedBook> borrowedBooks;
}
